name: API Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/docs/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup
      - name: Install dependencies
        run: pnpm install --filter=docs...
      - name: Build @noroff/api-docs
        run: pnpm turbo run build --filter=docs...
