# .github/workflows/docs_build.yml
name: API Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/docs/**
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup
      - name: Install dependencies
        run: pnpm install
      - name: Build @noroff/api-docs
        run: "pnpm build:docs"
